### ISSUE TITLE
Cannot install as per documentation

### ISSUE THREAD

**Issue by mathuin** [google/shenzhen-go#12]
`README.md` provides a command for installation.  When I run it on Ubuntu 16.04 LTS, it does not work.

```
$ go get -u github.com/google/shenzhen-go/cmd/shenzhen-go
# github.com/google/shenzhen-go/graph
go/src/github.com/google/shenzhen-go/graph/graph.go:114: enc.SetIndent undefined (type *json.Encoder has no field or method SetIndent)
$ uname -a
Linux nala 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l

$ go version
go version go1.6.2 linux/amd64
```

Please let me know if there's anything else I can do to help diagnose the issue.  This looks super fun!

**Comment by shurcooL** [comment]
From the error message, I can tell the problem is that shenzhen-go requires Go 1.7+, but you have 1.6. `SetIndent` is a method that was added to `encoding/json.Encoder` in 1.7.
