### ISSUE TITLE
get ride of all OS non agnostic code - use Mage instead

### ISSUE THREAD

**Issue by gedw99** [google/shenzhen-go#36]
saw the ps1 fiel for the client.

You can use Mage to get ride of all this !
https://github.com/magefile/mage

Mage is sort of like Makefiles but for golang.
You can also use them non compiled, but then compiel the mage file to have it non interpreted (not the right term i know, but you get the idea ) and not need golang installed.

Lost of golang programs using it.

Some great examples here:
https://github.com/mcandre/mage-extras

There are many other examples around.

Will be pretty quick to convert the stuff too.

**Comment by DrJosh9000** [comment]
Yep, I'm feeling good about mage.
